repo_url: https://privacyguides.github.io/fdroid/fdroid/repo
repo_name: Privacy Guides
repo_description: >-
   An F-Droid repository from Privacy Guides

repo_keyalias: KEYALIAS

keystore: keystore.keystore

keystorepass: "KEYSTORE_PASS"

keypass: "KEY_PASS"

keydname: KEYDNAME
